title: Engincan Veske - Personal Blog
author: EngincanV
email: enginveske@gmail.com
description: >
  Hi, I am Engincan VESKE. 
  I am a software engineer with 4+ years of experience. 
  I like to read, research and take notes. 
  Also, I like to share what I've learned in my blog. 
  I regularly write articles on medium (in Turkish), dev.to and community.abp.io (in English). 
show_excerpts: true

sass:
  sass_dir: _sass
plainwhite:
  name: Engincan Veske
  tagline: Software Engineer. 
  Team member of ABP Framework.
  date_format: "%b %-d, %Y"
  sitemap: true 
  search: true 
  dark_mode: true 
  portfolio_image: "assets/portfolio.png" 
  html_lang: "en" 
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    twitter: EngincanVeske
    github:  EngincanV
    linkedIn: in/engincanv
    stackoverflow: users/10477283/engincan-veske
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

plugins:
  - jekyll-seo-tag

remote_theme: samarsault/plainwhite-jekyll